name: Scheduled API Tests

on:
  #schedule:
    # Runs every 2 minutes
    #- cron: '*/2 * * * *'
  # Allow manual trigger from the Actions tab
  workflow_dispatch:

jobs:
  scheduled-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Run tests with Maven
        run: mvn clean test

      - name: Upload test artifacts (logs, reports, responses)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts-${{ github.run_id }}
          path: src/test/resources/test-artifacts/

      - name: Upload Cucumber report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-report-${{ github.run_id }}
          path: target/cucumber-reports/

      - name: Upload Surefire results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports-${{ github.run_id }}
          path: target/surefire-reports/
